name: strata-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - openjdk=17
  - yfinance
  - pydantic
  - pandas
  - numpy
  - pyarrow
  - pyyaml
  - requests
  - boto3
  - awscli
  - loguru
  - pyspark=3.5.1
