pipeline:

  engine: spark

compute:

  spark:

    master: yarn

storage:
  # Tenmporary placeholder the bucket is not created yet
  bronze: s3://strata-data/bronze
  silver: s3://strata-data/silver
  gold: s3://strata-data/gold
